---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r}
library(tidyverse)
library(dsbox)
```

```{r}
lego_sales %>%
  count(first_name, sort = TRUE)

## three most common names: Jackson, Jacob, Joseph
```

```{r}
lego_sales %>%
  count(theme, sort = TRUE)

## 4 most commonly purchased themes: Gear, Star Wars, Nexo Knights, Mixels
```

```{r}
lego_sales %>%
  filter(theme == "Star Wars") %>%
  count(subtheme, sort = TRUE)

## most common subtheme among the most common theme: The Force Awakens 
```

```{r}
lego_sales <- lego_sales %>%
  mutate(age_group = case_when(
    age <= 18 ~ "18 and under",
    age >= 19 & age <= 25 ~ "19 - 25",
    age >= 26 & age <= 35 ~ "26 - 35",
    age >= 36 & age <= 50 ~ "36 - 50",
    age >= 51 ~ "51 and over"
  ))
```

```{r}
lego_sales %>%
  count(age_group, sort = TRUE)

## most common age group: 36-50
```

```{r}
lego_sales %>%
  group_by(age_group) %>%
  summarise(
    total_n = sum(quantity)
  ) %>%
  arrange(desc(total_n))

## age group with most purchases: 36-50
```

```{r}
lego_sales %>%
  mutate(
    amount_spent = us_price * quantity
  ) %>%
  group_by(age_group) %>%
  summarise(
    total_spent = sum(amount_spent)
  ) %>%
  arrange(desc(total_spent))

## spent most money on lego sets: 36-50
```




























